services:
  # 컨테이너 내부의 node_modules 는 공유를 안 한다.
  # docker exec -it atchu-fe-feature sh -lc "npm install"
  atchu-fe-feature:
    build:
      context: ./02_fe_react
      dockerfile: Dockerfile
    image: atchu-fe:local
    container_name: atchu-fe-feature
    profiles:
      - feature
    ports:
      - "4020:5173"
    volumes:
      - ./02_fe_react:/app
      - /app/node_modules

  atchu-nginx-feature:
    image: nginx:1.27-alpine
    container_name: atchu-nginx-feature
    profiles:
      - feature
    depends_on:
      - atchu-fe-feature
    ports:
      - "4010:443"
    volumes:
      - ./01_proxy_nginx/nginx-feature.conf:/etc/nginx/conf.d/default.conf:ro
      - ./01_proxy_nginx/pem:/pem:ro

  atchu-nginx-prod:
    image: nginx:1.27-alpine
    container_name: atchu-nginx-prod
    profiles:
      - prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./01_proxy_nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./01_proxy_nginx/pem:/pem:ro
      - ./02_fe_react/dist:/usr/share/nginx/html:ro
